version: '3.6'
services:
  pgDB:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: sucasa
volumes:
  db_data:
